REGIONS:
  playing_left:
    - [499, 440]
    - [1067, 671]
  playing_middle:
    - [722, 591]
    - [1538, 720]
  playing_right:
    - [1176, 437]
    - [1716, 653]
  my_cards:
    - [493, 737]
    - [1723, 965]
  avatar_left:
    - [560, 300]
    - [690, 430]
  avatar_middle:
    - [972, 760]
    - [1110, 900]
  avatar_right:
    - [1510, 300]
    - [1640, 430]

GAME_WINDOW:
  OFFSET_X: 483
  OFFSET_Y: 237

THRESHOLDS:
  card: 0.95
  landlord: 0.95
  pass: 0.9
  wait: 0.9

SCREENSHOT_INTERVAL: 0.1
GAME_START_INTERVAL: 1.0

GUI:
  MAIN:
    DISPLAY: true
    OPACITY: 1.0
    FONT_SIZE: 25
    OFFSET_Y: 237
    CENTER_X: 1183
  LEFT:
    DISPLAY: true
    OPACITY: 0.9
    FONT_SIZE: 18
    CENTER_X: 688
    CENTER_Y: 693
  RIGHT:
    DISPLAY: true
    OPACITY: 0.9
    FONT_SIZE: 18
    OFFSET_X: 1933
    CENTER_Y: 693
  SWITCH:
    FONT_SIZE: 12
    OFFSET_X: 1683
    OFFSET_Y: 237

HOTKEYS:
  QUIT: q
  OPEN_LOG: l
  OPEN_SETTINGS: c
  RESET: r

LOG_LEVEL: INFO
LOG_RETENTION: 3
