REGIONS:
  playing_left:
  - - 206
    - 246
  - - 703
    - 433
  playing_middle:
  - - 320
    - 410
  - - 1136
    - 539
  playing_right:
  - - 737
    - 240
  - - 1193
    - 431
  my_cards:
  - - 87
    - 552
  - - 1301
    - 758
  avatar_left:
  - - 91
    - 264
  - - 222
    - 427
  avatar_middle:
  - - 81
    - 668
  - - 247
    - 815
  avatar_right:
  - - 1183
    - 268
  - - 1339
    - 434
  game_over:
  - - 106
    - 138
  - - 1320
    - 703
GAME_WINDOW:
  OFFSET_X: 81
  OFFSET_Y: 56
THRESHOLDS:
  card: 0.7
  landlord: 0.9
  pass: 0.8
  wait: 0.8
  gameover: 0.9
SCREENSHOT_INTERVAL: 0.1
GAME_START_INTERVAL: 1.0
TEMPLATE_SCALES:
- 0.75
- 0.8
- 0.85
- 0.9
- 0.95
- 1.0
- 1.05
- 1.1
- 1.15
- 1.2
- 1.25
- 1.3
- 1.4
- 1.5
GUI:
  MAIN:
    DISPLAY: true
    OPACITY: 1.0
    FONT_SIZE: 25
    CENTER_X: 700
    OFFSET_Y: 657
    OFFSET_X: -8
  LEFT:
    DISPLAY: true
    OPACITY: 0.9
    FONT_SIZE: 18
    CENTER_X: 205
    CENTER_Y: 456
  RIGHT:
    DISPLAY: true
    OPACITY: 0.9
    FONT_SIZE: 18
    OFFSET_X: 1450
    CENTER_Y: 456
  SWITCH:
    FONT_SIZE: 12
    OFFSET_X: 1069
    OFFSET_Y: 44
HOTKEYS:
  QUIT: q
  OPEN_LOG: l
  OPEN_SETTINGS: c
  RESET: r
LOG_LEVEL: INFO
LOG_RETENTION: 3
